server:
  port: 9092

spring:
  datasource:
    url: jdbc:sqlite:C:/Project/pet_name/database/pets_database.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLiteDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

